          version: 0.2
          phases:
            build:
              commands:
                - pip install pytz -t code
                - zip -j-r -9 ec2rds-scheduler.zip code/*
            post_build:
              commands:
                - aws cloudformation package --template-file EC2RDS-Scheduler.yaml --s3-bucket $BucketName --output-template-file packaged.yaml
          artifacts:
            files:
              - ec2-scheduler.zip
              - packaged.yaml
              - '*.json'